<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My albums';
 $this->headTitle($title);
 ?>

 <?php
//echo $this->inlineScript()->prependFile($this->basePath() . '/js/jquery.min.js')
echo $this->inlineScript()->prependFile($this->basePath() . '/js/alpbumprocessing.js');
                          //->prependFile($this->basePath() . '/js/test.js');
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('album', array('action'=>'add'));?>" class="albumadd">Add new album</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($album->title);?></td>
     <td><?php echo $this->escapeHtml($album->artist);?></td>
     <td>
         <a id="<?php echo $album->id;?>" href="<?php echo $this->url('album',
             array('action'=>'edit', 'id' => $album->id));?>" class="albumedit">Edit</a>
         <a href="<?php echo $this->url('album',
             array('action'=>'delete', 'id' => $album->id));?>" class="albumdelete">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
