<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My albums';
 $this->headTitle($title);
 ?>
<!-- css -->
<!-- the custom UI is based on jQueryUI theme you've downloaded -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/js/jqueryui/jquery-ui.theme.css'); ?>
<!-- Js -->
<?php  $this->headScript()
    ->appendFile($this->basePath() . '/js/jqueryui/jquery-ui.js')
    ->appendFile($this->basePath() . '/js/albumajaxform.js'); ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
<!--     <a href="--><?php //echo $this->url('album', array('action'=>'add'));?><!--">Add new album</a>-->
     <a id="showform" href="<?php echo $this->url('album',
         array('action'=>'showform', 'controller'=>'albumAnot')); ?>">Show Form</a>


 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($album->title);?></td>
     <td><?php echo $this->escapeHtml($album->artist);?></td>
     <td>
         <a class="editform" href="<?php echo $this->url('album',
             array('action'=>'showform', 'controller'=>'albumAnot', 'id' => $album->id));?>">Edit</a>
         <a href="<?php echo $this->url('album',
             array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
<!-- empty div to save dialog temporary -->
<div id="winpopup"></div>